### PR TITLE
lesson_1_8

### PR DESCRIPTION
**Pull request by daria1911**

### CODE REVIEW

**Review by achasek — APPROVED** [review]
your work on the lesson looks good so far. I assume you will be pushing the rest later?

**Comment by daria1911** [comment]
Yes. Do you mean another lessons or something else for this one ?

**Comment by achasek** [comment]
I just saw that on Airtable that you had the completion as 0-25%. If you finished the whole lesson, then I can go in and change that for you real quick.

**Comment by daria1911** [comment]
Yeah, I think I did everything that it was on a lesson , I think I accidentally marked as 25%.

**Comment by achasek** [comment]
Oh for sure. Ill go and change that for you. It looked like everything was done when I was checking it out, so I was definitely confused there heh

**Comment by daria1911** [comment]
Thank you

**Pull request merged**
